apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: gitops
spec:
  crossplane:
    version: ">=v1.0.0"
  dependsOn:
  - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
    version: ">=v0.13.0"
  - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
    version: ">=v0.8.0"