apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xlocalgitops.irizzant.it
spec:
  group: irizzant.it
  names:
    kind: XLocalGitops
    plural: xlocalgitops
  claimNames:
    kind: LocalGitops
    plural: localgitops
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: {}