apiVersion: irizzant.it/v1alpha1
kind: GitOps
metadata:
    name: gitops
spec:
    gitOpsRepo: https://github.com/irizzante/management-cluster.git
    providerConfigName:
        helm: helm-provider
        kubernetes: kubernetes-provider