envName: management

default:
  app:
    syncOptions: |
      - PruneLast=true
      - CreateNamespace=true

applications:
  external-secrets:
    enabled: true
    destination:
      namespace: external-secrets
    source:
      path: cluster-addons/envs/management/external-secrets
  
  nginx:
    enabled: true
    destination:
      namespace: nginx
    sources: |
      - repoURL: 'https://kubernetes.github.io/ingress-nginx'
        targetRevision: {{ $.Values.applications.nginx.source.targetRevision }}
        chart: ingress-nginx
        helm:
          valueFiles:
          - $values/cluster-addons/base/nginx/values.yaml
          - $values/cluster-addons/variants/prod/nginx/values-prod.yaml
          - $values/cluster-addons/variants/prod/nginx/replicas.yaml
          - $values/cluster-addons/envs/{{ $.Values.envName }}/nginx/values-{{ $.Values.envName }}.yaml
          - $values/cluster-addons/envs/{{ $.Values.envName }}/nginx/replicas.yaml
      - repoURL: 'https://github.com/irizzante/management-cluster.git'
        targetRevision: main
        ref: values
    source:
      targetRevision: 4.7.0

  prometheus:
    enabled: true
    destination:
      namespace: monitoring
    sources: |
      - repoURL: 'https://prometheus-community.github.io/helm-charts'
        targetRevision: {{ $.Values.applications.prometheus.source.targetRevision }}
        chart: kube-prometheus-stack
        helm:
          valueFiles:
          - $values/cluster-addons/base/prometheus/values.yaml
          - $values/cluster-addons/variants/prod/prometheus/values-prod.yaml
      - repoURL: 'https://github.com/irizzante/management-cluster.git'
        targetRevision: main
        ref: values
    source:
      targetRevision: 46.4.1
    