apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/irizzante/management-cluster.git
      revision: HEAD
      directories:
      - path: cluster-addons/envs/management/*
  template:
    metadata:
      name: 'addon-{{path.basename}}'
      namespace: argocd
    spec:
      project: platform
      source:
        repoURL: https://github.com/irizzante/management-cluster.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: true