apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: cluster-addons/base/apps
    repoURL: 'https://github.com/irizzante/management-cluster.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - cluster-addons/variants/prod/apps/values-prod.yaml
      - cluster-addons/envs/management/apps/values-management.yaml
  project: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
