apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vclusters
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/irizzante/management-cluster.git
      revision: HEAD
      directories:
      - path: vclusters/*
  template:
    metadata:
      name: 'vcluster-{{path.basename}}'
      namespace: argocd
    spec:
      project: platform
      source:
        repoURL: https://github.com/irizzante/management-cluster.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: vclusters
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true