envName: null

default:
  app:
    destination:
      server: https://kubernetes.default.svc
    project: platform
    source:
      repoURL: https://github.com/irizzante/management-cluster.git
      targetRevision: HEAD
    enableAutoSync: true
    selfHeal: true
    autoSyncPrune: true

applications:
  external-secrets:
    enabled: true
    destination:
      namespace: external-secrets
  
  nginx:
    enabled: true
    destination:
      namespace: nginx
  
  prometheus:
    enabled: true
    destination:
      namespace: monitoring
    syncOptions: |
      - PruneLast=true
      - CreateNamespace=true
      - ServerSideApply=true