apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/prometheus

components:
- ../../../variants/non-prod/prometheus

patches:
- patch: |-
    - op: add
      path: /spec/sources/0/helm/valueFiles/-
      value: $values/cluster-addons/envs/management/prometheus/values-vclusters.yaml
  target:
    kind: Application
    name: prometheus
- path: version.yaml
  target:
    kind: Application
    name: prometheus
