apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/external-secrets

components:
- ../../../variants/prod/external-secrets

patches:
- patch: |-
    - op: add
      path: /spec/sources/0/helm/valueFiles/-
      value: $values/cluster-addons/envs/management/external-secrets/values-management.yaml
  target:
    kind: Application
    name: external-secrets
- path: version.yaml
  target:
    kind: Application
    name: external-secrets