apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmanagementclusterapps.irizzant.it
spec:
  group: irizzant.it
  names:
    kind: XManagementClusterApps
    plural: xmanagementclusterapps
  claimNames:
    kind: ManagementClusterApps
    plural: managementclusterapps
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: {}