apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xmanagementclusterapps.irizzant.it
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: irizzant.it/v1alpha1
    kind: XManagementClusterApps
  resources:
    - name: helm-provider-config
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        metadata:
          name: helm-provider
        spec:
          credentials:
            source: InjectedIdentity
    - name: k8s-provider-config
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        metadata:
          name: kubernetes-provider
        spec:
          credentials:
            source: InjectedIdentity
    - name: argocd-chart
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: argocd
        spec:
          providerConfigRef:
            name: helm-provider
          forProvider:
            chart:
              name: wordpress
              repository: https://argoproj.github.io/argo-helm
              version: 5.34.1
            namespace: argocd
            values:
              redis-ha:
                enabled: true
              controller:
                replicas: 1
              server:
                autoscaling:
                  enabled: true
                  minReplicas: 2
              repoServer:
                autoscaling:
                  enabled: true
                  minReplicas: 2
              applicationSet:
                replicaCount: 2
              configs:
                cm:
                  application.resourceTrackingMethod: annotation
          connectionDetails:
          - apiVersion: v1
            kind: Secret
            name: argocd-initial-admin-secret
            namespace: argocd
            fieldPath: data.password
            toConnectionSecretKey: argocd-password
            skipPartOfReleaseCheck: true
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-argocd"
      connectionDetails:
        - fromConnectionSecretKey: argocd-password        
