apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: local-gitops
spec:
  package: irizzant/localgitops:0.1.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1