controller:
  hostPort:
    enabled: true
  service:
    type: ClusterIP
  tolerations:
  - key: "node-role.kubernetes.io/control-plane:NoSchedule"
    operator: "Exists"
    effect: "NoSchedule"

  nodeSelector:
    ingress-ready: "true"