apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: version.yaml
  target:
    kind: Application
    name: prometheus
- patch: |-
    - op: add
      path: /spec/sources/0/helm/valueFiles/-
      value: $values/cluster-addons/variants/non-prod/prometheus/values-non-prod.yaml
  target:
    kind: Application
    name: prometheus