apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vclusters-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    gitlab:
      groupIDs: 
      - "123456"