apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: envs-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/irizzante/management-cluster.git
      revision: HEAD
      directories:
      - path: apps/lib/envs/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: platform
      source:
        path: apps/
        repoURL: https://github.com/irizzante/management-cluster.git
        targetRevision: HEAD
        plugin:
          env:
          - name: TK_ENV
            value: default
          - name: TK_EXTRA_ARGS
            value: --name={{path.basename}}
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
