apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vclusters-secret-store
  namespace: external-secrets
spec:
  provider:
    gitlab:
      groupIDs: 
      - "68237223"