apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    - op: add
      path: /spec/sources/0/helm/valueFiles/-
      value: $values/cluster-addons/variants/prod/nginx/values-prod.yaml
  target:
    kind: Application
    name: nginx
- path: version.yaml
  target:
    kind: Application
    name: nginx